name: flutter_i18n
description: i18n made easy for Flutter. With flutter_i18n you can make your app international, using just a simple .json file!
version: 0.3.0
homepage: https://github.com/ilteoood/flutter_i18n
issue_tracker: https://github.com/ilteoood/flutter_i18n/issues

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.16.1
  yaml: ^2.2.1
  xml2json: ^4.4.0
  path: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

environment:
  sdk: '>=2.10.5 <3.0.0'
